---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no


   tasks:

   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - epel-release
         - nano
         - net-tools
         - tcpdump
         - nmap
         - wireshark
         - git
         - wget
         - iproute
         - psmisc
         - chrony
         - telnet
         - iptables-services
         - yum-utils
         - device-mapper-persistent-data
         - lvm2
       state: latest


 #  - name: Install EPEL repo
 #    yum_repository:
 #      name: CentOS-Extras
 #      description: "Centos 7 Extras"
 #      baseurl: "http://mirror.centos.org/centos/7/extras/x86_64/"
 #      gpgcheck: yes
 #      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7


   - name: Install Docker-repo
     tags: repo
     shell: "yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo"

#   - name: Add Docker repo
#     get_url:
#       url: https://download.docker.com/linux/centos/docker-ce.repo
#       dest: /etc/yum.repos.d/docker-ce.repo


   - name: Install Docker Engine
     tags: engine
     yum:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest


   - name: Install Docker-compose
     tags: compose 
     shell: "curl -L \"https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"

   - name: Moving stuff
     tags: move
     shell: "mv /usr/local/bin/docker-compose /usr/bin/docker-compose"

   - name: Add permissions for compose directory
     tags: perm
     shell: "chmod +x /usr/local/bin/docker-compose"


   - name: Start Docker daemon
     tags: systemctl
     systemd:
       name: docker
       state: started
       enabled: yes
       masked: no

