---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no


   tasks:

   - name: Update the machine
     tags: upd
     yum:
       update_only: yes

   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - epel-release
         - nano
         - net-tools
         - tcpdump
         - nmap
         - git
         - wget
         - iproute
         - psmisc
         - chrony
         - telnet
         - iptables-services
         - dnsmasq
         - syslinux
         - tftp-server
         - vsftpd
       state: latest

   - name: Set NTP & copy backup "dnsmasq.conf" file
     shell: |
       timedatectl set-ntp true
       timedatectl set-timezone Europe/Berlin
       cp /etc/dnsmasq.conf  /etc/ backup-dnsmasq.conf
       echo "" > /etc/dnsmasq.conf


   - name: Create dnsmasq file 
     tags:
     ansible.builtin.template:
       src: /root/Automated_Tasks/files/dnsmasq.txt
       dest: /etc/dnsmasq.conf
       owner: root
       mode: '755'


   - name: Create and copy some files
     shell: |
       cp -r /usr/share/syslinux/* /var/lib/tftpboot
       mkdir /var/lib/tftpboot/pxelinux.cfg
       touch /var/lib/tftpboot/pxelinux.cfg/default

  
   - name: Create default file 
     tags:
     ansible.builtin.template:
       src: /root/Automated_Tasks/files/default.txt
       dest: /var/lib/tftpboot/pxelinux.cfg/default
       owner: root
       mode: '755'

   - name: Download CentOS-7 minimal Image
     get_url:
       url: http://mirror.imt-systems.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
       dest: /root/

•	cd  /dev/
•	chmod 777 loop0
•	mount -o loop /path/to/centos-dvd.iso  /mnt
•	mkdir /var/lib/tftpboot/centos7
•	cp /mnt/images/pxeboot/vmlinuz  /var/lib/tftpboot/centos7
•	cp /mnt/images/pxeboot/initrd.img  /var/lib/tftpboot/centos7
•	


•	cp -r /mnt/*  /var/ftp/pub/ 
•	systemctl start dnsmasq
•	systemctl status dnsmasq
•	systemctl start vsftpd
•	systemctl status vsftpd
•	systemctl enable dnsmasq
•	systemctl enable vsftpd



•	firewall-cmd --add-service=ftp --permanent  	## Port 21
•	firewall-cmd --add-service=dns --permanent  	## Port 53
•	firewall-cmd --add-service=dhcp --permanent  	## Port 67
•	firewall-cmd --add-port=69/udp --permanent  	## Port for TFTP
•	firewall-cmd --add-port=4011/udp --permanent  ## Port for ProxyDHCP
•	firewall-cmd --reload  ## Apply rules

•	umount /mnt



#   - name: Add Docker repo
#     get_url:
#       url: https://download.docker.com/linux/centos/docker-ce.repo
#       dest: /etc/yum.repos.d/docker-ce.repo


#   - name: 
#     tags:  
#     shell: 


#   - name: Start 
#     tags: systemctl
#     systemd:
#       name: 
#       state: started
#       enabled: yes
#       masked: no

