---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no


   tasks:

   - name: Update the machine
     tags: upd
     yum:
       update_only: yes

   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - epel-release
         - nano
         - net-tools
         - tcpdump
         - nmap
         - git
         - wget
         - iproute
         - psmisc
         - chrony
         - telnet
         - iptables-services
         - dnsmasq
         - syslinux
         - tftp-server
         - vsftpd
         - pykickstart
       state: latest

   - name: Set NTP & copy backup "dnsmasq.conf" file
     tags: NTP
     shell: |
       timedatectl set-ntp true
       timedatectl set-timezone Europe/Berlin
       cp /etc/dnsmasq.conf  /etc/backup-dnsmasq.conf


   - name: Create dnsmasq file 
     tags: dnsmasq
     ansible.builtin.template:
       src: /root/Automated_Tasks/files/dnsmasq.txt
       dest: /etc/dnsmasq.conf
       owner: root
       mode: '644'


   - name: Create and copy some files
     tags: pxe
     shell: |
       cp -r /usr/share/syslinux/* /var/lib/tftpboot
       mkdir /var/lib/tftpboot/pxelinux.cfg
       
      
   - name: Create default file 
     tags: pxe, dafault
     ansible.builtin.template:
       src: /root/Automated_Tasks/files/default.txt
       dest: /var/lib/tftpboot/pxelinux.cfg/default
       owner: root
       mode: '644'

   - name: Download CentOS-7 minimal Image
     tags: url
     get_url:
       url: http://mirror.imt-systems.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
       dest: /root/

